@hostname = localhost
@port = 5115
@host = http://{{hostname}}:{{port}}

### Realizar Checkin com vaga aleatória
POST {{host}}/api/ticket/checkin
Content-Type: application/json

{
  "licensePlate": "BRA2E24",
  "model": "Onix",
  "color": "Branco",
  "parkingSpotId": null
}

### Realizar Check-in com vaga específica
POST {{host}}/api/ticket/checkin
Content-Type: application/json

{
  "licensePlate": "BRA3K56",
  "model": "HB20",
  "color": "Preto",
  "parkingSpotId": 3
}


### Ver vagas (Dashboard)
GET {{host}}/api/parkingspot/dashboard

### Simular Check-out (Preview)
GET {{host}}/api/ticket/checkout/preview/1

### Confirmar Check-out
POST {{host}}/api/ticket/checkout/1
Content-Type: application/json

{
	"exitTime": ""
}
